### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by khatchad** [frankcortes/svn-stash#1]
``` bash
svn-stash
Traceback (most recent call last):
  File "/usr/local/svn-stash/svn-stash.py", line 126, in <module>
    main(sys.argv)
  File "/usr/local/svn-stash/svn-stash.py", line 121, in main
    filename_list = obtain_svn_status_files()
  File "/usr/local/svn-stash/svn-stash.py", line 107, in obtain_svn_status_files
    (status,filename) = line.split()
ValueError: too many values to unpack
```

**Comment by frankcortes** [comment]
I have resolved the problem with the unpack if the split returns more than a two values, although I don't know the concrete use case. If you can reproduce the subversion status, I will be grateful for this :p
